### ISSUE TITLE
Release for weak_framework

### ISSUE THREAD

**Issue by olgeni** [semlette/nfc_in_flutter#32]
Hello,

Would it be possible to roll a release with commit 3041739? So I could get NFC as a weak framework, and use the app on older phones too 😅

**Comment by semlette** [comment]
I'll try to get a release out shortly. There's a few things I want to sort out before I publish a new release, but in the mean time you can set the nfc_in_flutter version to the Git commit like so:
```yaml
dependencies:
  nfc_in_flutter:
    git:
      url: git://github.com/semlette/nfc_in_flutter.git
      ref: 4c1b73f5d024fac7d25ac909f5d47796a53e5e3e
```
